import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'
import router from './routes/router'
import './static/inquiry.css'
import './static/main.bundle.css'
import './static/startup-element.css'
import './static/style.css'
createApp(App).use(ElementPlus).use(router).mount('#app')
